INSERT INTO Nazioni (idSigla,nomeNazione) VALUES 
('AF','Afghanistan'),
('AL','Albania'),
('DZ','Algeria'),
('AD','Andorra'),
('AO','Angola'),
('AI','Anguilla'),
('AQ','Antartide'),
('AG','Antigua e Barbuda'),
('AN','Antille Olandesi'),
('SA','Arabia Saudita'),
('AR','Argentina'),
('AM','Armenia'),
('AW','Aruba'),
('AU','Australia'),
('AT','Austria'),
('AZ','Azerbaijan'),
('BS','Bahamas'),
('BH','Bahrain'),
('BD','Bangladesh'),
('BB','Barbados'),
('BE','Belgio'),
('BZ','Belize'),
('BJ','Benin'),
('BM','Bermuda'),
('BY','Bielorussia'),
('BT','Bhutan'),
('BO','Bolivia'),
('BA','Bosnia Erzegovina'),
('BW','Botswana'),
('BR','Brasile'),
('BN','Brunei Darussalam'),
('BG','Bulgaria'),
('BF','Burkina Faso'),
('BI','Burundi'),
('KH','Cambogia'),
('CM','Camerun'),
('CA','Canada'),
('CV','Capo Verde'),
('TD','Ciad'),
('CL','Cile'),
('CN','Cina'),
('CY','Cipro'),
('VA','Citta del Vaticano'),
('CO','Colombia'),
('KM','Comore'),
('KP','Corea del Nord'),
('KR','Corea del Sud'),
('CR','Costa Rica'),
('CI',"Costa d'Avorio"),
('HR','Croazia'),
('CU','Cuba'),
('DK','Danimarca'),
('DM','Dominica'),
('EC','Ecuador'),
('EG','Egitto'),
('IE','Eire'),
('SV','El Salvador'),
('AE','Emirati Arabi Uniti'),
('ER','Eritrea'),
('EE','Estonia'),
('ET','Etiopia'),
('RU','Federazione Russa'),
('FJ','Fiji'),
('PH','Filippine'),
('FI','Finlandia'),
('FR','Francia'),
('GA','Gabon'),
('GM','Gambia'),
('GE','Georgia'),
('DE','Germania'),
('GH','Ghana'),
('JM','Giamaica'),
('JP','Giappone'),
('GI','Gibilterra'),
('DJ','Gibuti'),
('JO','Giordania'),
('GR','Grecia'),
('GD','Grenada'),
('GL','Groenlandia'),
('GP','Guadalupa'),
('GU','Guam'),
('GT','Guatemala'),
('GN','Guinea'),
('GW','Guinea-Bissau'),
('GQ','Guinea Equatoriale'),
('GY','Guyana'),
('GF','Guyana Francese'),
('HT','Haiti'),
('HN','Honduras'),
('HK','Hong Kong'),
('IN','India'),
('ID','Indonesia'),
('IR','Iran'),
('IQ','Iraq'),
('BV','Isola di Bouvet'),
('CX','Isola di Natale'),
('HM','Isola Heard e Isole McDonald'),
('KY','Isole Cayman'),
('CC','Isole Cocos'),
('CK','Isole Cook'),
('FK','Isole Falkland'),
('FO','Isole Faroe'),
('MH','Isole Marshall'),
('MP','Isole Marianne Settentrionali'),
('UM',"Isole Minori degli Stati Uniti d'America"),
('NF','Isola Norfolk'),
('SB','Isole Solomon'),
('TC','Isole Turks e Caicos'),
('VI','Isole Vergini Americane'),
('VG','Isole Vergini Britanniche'),
('IL','Israele'),
('IS','Islanda'),
('IT','Italia'),
('KZ','Kazakhistan'),
('KE','Kenya'),
('KG','Kirghizistan'),
('KI','Kiribati'),
('KW','Kuwait'),
('LA','Laos'),
('LV','Lettonia'),
('LS','Lesotho'),
('LB','Libano'),
('LR','Liberia'),
('LY','Libia'),
('LI','Liechtenstein'),
('LT','Lituania'),
('LU','Lussemburgo'),
('MO','Macao'),
('MK','Macedonia'),
('MG','Madagascar'),
('MW','Malawi'),
('MV','Maldive'),
('MY','Malesia'),
('ML','Mali'),
('MT','Malta'),
('MA','Marocco'),
('MQ','Martinica'),
('MR','Mauritania'),
('MU','Maurizius'),
('YT','Mayotte'),
('MX','Messico'),
('MD','Moldavia'),
('MC','Monaco'),
('MN','Mongolia'),
('MS','Montserrat'),
('MZ','Mozambico'),
('MM','Myanmar'),
('NA','Namibia'),
('NR','Nauru'),
('NP','Nepal'),
('NI','Nicaragua'),
('NE','Niger'),
('NG','Nigeria'),
('NU','Niue'),
('NO','Norvegia'),
('NC','Nuova Caledonia'),
('NZ','Nuova Zelanda'),
('OM','Oman'),
('NL','Paesi Bassi'),
('PK','Pakistan'),
('PW','Palau'),
('PA','Panama'),
('PG','Papua Nuova Guinea'),
('PY','Paraguay'),
('PE','Peru'),
('PN','Pitcairn'),
('PF','Polinesia Francese'),
('PL','Polonia'),
('PT','Portogallo'),
('PR','Porto Rico'),
('QA','Qatar'),
('GB','Regno Unito'),
('CZ','Repubblica Ceca'),
('CF','Repubblica Centroafricana'),
('CG','Repubblica del Congo'),
('CD','Repubblica Democratica del Congo'),
('DO','Repubblica Dominicana'),
('RE','Reunion'),
('RO','Romania'),
('RW','Ruanda'),
('EH','Sahara Occidentale'),
('KN','Saint Kitts e Nevis'),
('PM','Saint Pierre e Miquelon'),
('VC','Saint Vincent e Grenadine'),
('WS','Samoa'),
('AS','Samoa Americane'),
('SM','San Marino'),
('SH',"Sant'Elena"),
('LC','Santa Lucia'),
('ST','Sao Tome e Principe'),
('SN','Senegal'),
('XK','Kosovo'),
('SC','Seychelles'),
('SL','Sierra Leone'),
('SG','Singapore'),
('SY','Siria'),
('SK','Slovacchia'),
('SI','Slovenia'),
('SO','Somalia'),
('ES','Spagna'),
('LK','Sri Lanka'),
('FM','Stati Federati della Micronesia'),
('US',"Stati Uniti d'America"),
('ZA','Sud Africa'),
('GS','Sud Georgia e Isole Sandwich'),
('SD','Sudan'),
('SR','Suriname'),
('SJ','Svalbard e Jan Mayen'),
('SE','Svezia'),
('CH','Svizzera'),
('SZ','Swaziland'),
('TJ','Tagikistan'),
('TH','Tailandia'),
('TW','Taiwan'),
('TZ','Tanzania'),
('IO',"Territori Britannici dell'Oceano Indiano"),
('TF','Territori Francesi del Sud'),
('PS','Territori Palestinesi Occupati'),
('TL','Timor Est'),
('TG','Togo'),
('TK','Tokelau'),
('TO','Tonga'),
('TT','Trinidad e Tobago'),
('TN','Tunisia'),
('TR','Turchia'),
('TM','Turkmenistan'),
('TV','Tuvalu'),
('UA','Ucraina'),
('UG','Uganda'),
('HU','Ungheria'),
('UY','Uruguay'),
('UZ','Uzbekistan'),
('VU','Vanuatu'),
('VE','Venezuela'),
('VN','Vietnam'),
('WF','Wallis e Futuna'),
('YE','Yemen'),
('ZM','Zambia'),
('ZW','Zimbabwe'),
('RS','Serbia'),
('ME','Montenegro'),
('TP','Timor Est'),
('GG','Guernsey');