INSERT INTO tipologie (idTipologia,nomeTipologia) VALUES 
(1,'Socio ordinario'),
(2,'Socio sostenitore'),
(3,'Socio affiliato'),
(4,'Socio onorario'),
(5,'Socio junior'),
(6,'Socio under 18'),
(7,'Socio over 65'),
(8,'Socio a vita'),
(9,'Socio benemerito'),
(10,'Socio promotore'),
(11,'Socio sostenitore gold'),
(12,'Socio sostenitore platinum'),
(13,'Socio corporate'),
(14,'Socio corporate gold'),
(15,'Socio corporate platinum'),
(16,'Socio family'),
(17,'Socio family gold'),
(18,'Socio family platinum'),
(19,'Studente'),
(20,'Dottorando di ricerca'),
(21,'Ricercatore'),
(22,'Docente'),
(23,'Pensionato'),
(24,'Disoccupato'),
(25,'Casalinga'),
(26,'Volontario'),
(27,'Amico del museo'),
(28,'Amico della biblioteca'),
(29,'Amico della pinacoteca'),
(30,'Sostenitore dei progetti speciali'),
(31,"Donatore per il restauro di opere d'arte"),
(32,"Donatore per l'acquisto di nuove opere d'arte"),
(33,'Sponsor di una mostra'),
(34,'Sponsor di un evento'),
(35,'Partner istituzionale'),
(36,'Media partner'),
(37,'Fornitore'),
(38,'Cliente'),
(39,'Abbonato alla newsletter'),
(40,'Seguace sui social media'),
(41,'Partecipante a un evento'),
(42,'Iscritto a un corso'),
(43,'Utente del servizio online'),
(44,'Visitatore del sito web'),
(45,'Abbonato alla rivista'),
(46,'Acquirente di un prodotto'),
(47,'Partecipante a un sondaggio'),
(48,'Iscritto a un forum'),
(49,'Donatore per una campagna di raccolta fondi'),
(50,'Volontario per un progetto');